### ISSUE TITLE
In Video full screen mode user is able to record the screen 

### ISSUE THREAD

**Issue by RN-Dev-Shubh** [Praveencena88/react-native-prevent-screenshot-ios-android#2]
In ios when user start the recording and if the user play a video in full screen mode then in the recording video is showing. rather than showing the black background.

i am using 
```
if (Platform.OS == 'ios') {
  enableSecureView(); //This function blocks the Screen share/Recording and taking screenshot for iOS devices.
}
```

in the App.js file

**Comment by Praveencena88** [comment]
can you elaborate more or copy/paste the component code here, how it is implemented?

**Comment by Praveencena88** [comment]
closing because of no response
