### ISSUE TITLE
Remove placeholder on iOS

### ISSUE THREAD

**Issue by Dubemtopsite** [Praveencena88/react-native-prevent-screenshot-ios-android#4]
![image](https://github.com/Praveencena88/react-native-prevent-screenshot-ios-android/assets/31639636/d2789576-8b22-4699-be3a-371117517028)

![image](https://github.com/Praveencena88/react-native-prevent-screenshot-ios-android/assets/31639636/3bb56ef1-8f81-4364-9d2d-7025f356b699)

From the picture above I used enableSecureView on iOS but am the placeholder "This action has been restricted by your app" is appearing on the top of the app.

Please how can I remove it so that it will not overlap the app content?

**Comment by Praveencena88** [comment]
Please add background color to the respective screen and see, hope it works!!

**Comment by Praveencena88** [comment]
closing because of no response

**Comment by jgiovanni** [comment]
I'm also experiencing this issue, the text is above app UI . Adding a background color has not worked for me either. Is the placeholder text here necessary? 
`secureField.placeholder = @"This action has been restricted by your app.";`
https://github.com/Praveencena88/react-native-prevent-screenshot-ios-android/blob/main/ios/PreventScreenshotIosAndroid.mm#L117
