### ISSUE TITLE
I am using expo, can I implement in expo project? or do I need to eject from expo and move to CLI?

### ISSUE THREAD

**Issue by haziq786** [Praveencena88/react-native-prevent-screenshot-ios-android#6]

**Comment by Praveencena88** [comment]
No, you cannot directly use the react-native-prevent-screenshot-ios-android package in an Expo-managed workflow. Expo managed workflow doesn’t allow the use of native modules that require linking or custom native code out-of-the-box, and react-native-prevent-screenshot-ios-android is one of those native modules.
